Repository OpenAF/nAttrMon, pull requests merged in 2023-10, with the labels that each got.

#200 nInputShell
  .package.yaml
  config/inputs.disabled/yaml/12.shellProcCmd.yaml
  config/objects/nInput_Shell.js
Labels: bug, enhancement

#203 Update nInput_DB.js
  config/objects/nInput_DB.js
Labels: bug

#206 nOutput-NDJson s3sync
  config/objects/nOutput_NDJson.js
  config/outputs.disabled/yaml/10.ndjson.yaml
Labels: enhancement
